import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/styles/main.scss"
import Header from "@/components/Layout/Header"
import { NuqsAdapter } from "nuqs/adapters/next"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Frontend Task",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable}`}>
        <NuqsAdapter>
          <a href="#main-content" className="skip-link">
            Skip to main content
          </a>
          <Header />
          <main id="main-content" tabIndex={-1} className="app">
            {children}
          </main>
        </NuqsAdapter>
      </body>
    </html>
  )
}
